import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from "../components/BottomNav";
import Header from "../components/Header";
import SearchBar from "../components/SearchBar";
import Image from "next/image";
import { Button2 } from "../components/ui/Button2";
import whatsappIcon from "../assets/tab_icon/whatsapp.png";
import callIcon from "../assets/tab_icon/call.png";
import locationIcon from "../assets/tab_icon/location.png";
import streetviewIcon from "../assets/tab_icon/streetview.png";
import RotateToPortrait from "../components/utils/RotateToPortrait";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RotateToPortrait />
        <div className="min-h-screen bg-gradient-to-b from-violet-50 to-white flex flex-col items-center">
          <div className="w-full max-w-screen-2xl flex flex-col lg:flex-row">
            {/* Left Advertisement Space (Desktop) */}
            <div className="hidden lg:block w-48 bg-gray-200 p-4 text-center">
              <span className="text-gray-700 font-semibold">Advertisement</span>
            </div>
            {/* Main Container */}
            <div className="flex-1 bg-white shadow-xl min-h-screen pb-20 lg:pb-0 lg:flex">
              {/* Sticky Aside (Desktop) */}
              <aside className="hidden lg:block lg:w-56 lg:border-r lg:p-4 bg-violet-50 sticky top-0 h-screen">
                <div>
                  <a
                    href="#"
                    className="block py-2 px-4 rounded-lg text-violet-600 hover:bg-violet-100 transition-colors duration-200"
                  >
                    <Image
                      src="/logo4light.png"
                      alt="nearByBro Logo"
                      width={200}
                      height={50}
                    />
                  </a>
                </div>
                <h2 className="text-2xl font-bold mb-6 text-violet-800">
                  Menu
                </h2>
                <nav>
                  <ul className="space-y-2">
                    {["Home", "Bookings", "Calendar", "Inbox", "Profile"].map(
                      (item) => (
                        <li key={item}>
                          <a
                            href="#"
                            className="block py-2 px-4 rounded-lg text-violet-600 hover:bg-violet-100 transition-colors duration-200"
                          >
                            {item}
                          </a>
                        </li>
                      )
                    )}
                  </ul>
                </nav>
              </aside>

              {/* Main Content */}
              <main className="flex-1">
                {/* Fixed Header */}
                <div className="sticky top-0 bg-white z-10 shadow-md">
                  <Header />
                </div>
                <div className="px-4 md:px-6 lg:px-8 space-y-6 py-4">
                  <SearchBar />

                  {children}
                </div>
              </main>
            </div>
            {/* Right Advertisement Space (Desktop) */}
            <div className="hidden lg:block w-48 bg-gray-200 p-4 text-center">
              <div className="overflow-Y-scroll fixed  right-0 p-4 gap-4 max-w-2xl mx-auto ">
                <Button2
                  variant="outline"
                  className="min-w-8 flex items-center justify-center gap-2 bg-white"
                >
                  {/* <MessageCircleIcon className="w-4 h-4" />
          Whatsapp */}
                  <Image
                    src={whatsappIcon}
                    alt="whatsapp"
                    width={100}
                    height={100}
                  />
                </Button2>
                <Button2
                  variant="outline"
                  className="min-w-8 flex items-center justify-center gap-2 bg-white"
                >
                  {/* <CalendarIcon className="w-4 h-4" />
          Call Now */}
                  <Image src={callIcon} alt="call" width={100} height={100} />
                </Button2>
                <Button2
                  variant="outline"
                  className="min-w-8 flex items-center justify-center gap-2 bg-white"
                >
                  {/* <CalendarIcon className="w-4 h-4" />
          Location */}
                  <Image
                    src={locationIcon}
                    alt="location"
                    width={100}
                    height={100}
                  />
                </Button2>
                <Button2
                  variant="outline"
                  className="min-w-8 flex items-center justify-center gap-2 bg-white"
                >
                  {/* <CalendarIcon className="w-4 h-4" />
          Street View */}
                  <Image
                    src={streetviewIcon}
                    alt="location"
                    width={100}
                    height={100}
                  />
                </Button2>
              </div>
            </div>
          </div>

          {/* Bottom Advertisement (All Devices)
          <div className="w-full bg-gray-200 p-6 text-center mt-4">
            <span className="text-gray-700 font-semibold">Advertisement</span>
          </div> */}
        </div>
        <BottomNav />
      </body>
    </html>
  );
}
